name: flutter_dotenv
version: 2.0.2
description: Easily configure any flutter web application with global variables using a `.env` file.
author: java-james <james-collins@hotmail.co.nz>
homepage: https://github.com/java-james/flutter_dotenv
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter_web: any
  flutter_web_ui: any
  meta: ^1.1.6
dev_dependencies:
  # Enables the `pub run build_runner` command
  build_runner: ">=1.6.2 <2.0.0"
  # Includes the JavaScript compilers
  build_web_compilers: ">=1.2.0 <3.0.0"

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
